[main]
default=power-saver
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
power-saver=laptop-battery-powersave
balanced=balanced
performance=throughput-performance

[battery]
balanced=balanced-battery
