# Generated by sync-shell-theme. Source: Matugen.
set -g fish_color_normal eedfe2
set -g fish_color_command ffb0d0 --bold
set -g fish_color_keyword e1bdca
set -g fish_color_param eedfe2
set -g fish_color_option f1bb98
set -g fish_color_quote f1bb98
set -g fish_color_redirection e1bdca
set -g fish_color_end ffb0d0
set -g fish_color_error ffb4ab --bold
set -g fish_color_comment d4c2c7 --dim
set -g fish_color_operator e1bdca
set -g fish_color_escape f1bb98
set -g fish_color_autosuggestion 9d8c92
set -g fish_color_selection --background=864764
set -g fish_color_search_match --background=332a2d
set -g fish_color_valid_path --underline
set -g fish_pager_color_progress d4c2c7
set -g fish_pager_color_prefix ffb0d0 --bold
set -g fish_pager_color_completion eedfe2
set -g fish_pager_color_description d4c2c7
set -g fish_pager_color_selected_background --background=864764
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS --border=rounded --info=inline-right \
--color=fg:#eedfe2,bg:-1,hl:#ffb0d0 \
--color=fg+:#eedfe2,bg+:#332a2d,hl+:#ffb0d0 \
--color=info:#d4c2c7,prompt:#ffb0d0,pointer:#f1bb98 \
--color=marker:#e1bdca,spinner:#ffb0d0,header:#d4c2c7 \
--color=border:#66585d"
