# Generated by sync-shell-theme. Source: Mango theme palette.
set -g fish_color_normal 3c3836
set -g fish_color_command 076678 --bold
set -g fish_color_keyword 8f3f71
set -g fish_color_param 3c3836
set -g fish_color_option 427b58
set -g fish_color_quote 79740e
set -g fish_color_redirection b57614
set -g fish_color_end b57614
set -g fish_color_error cc241d --bold
set -g fish_color_comment 665c54 --dim
set -g fish_color_operator 427b58
set -g fish_color_escape 8f3f71
set -g fish_color_autosuggestion 928374
set -g fish_color_selection --background=d5c4a1
set -g fish_color_search_match --background=d5c4a1
set -g fish_color_valid_path --underline
set -g fish_pager_color_progress 665c54
set -g fish_pager_color_prefix b57614 --bold
set -g fish_pager_color_completion 3c3836
set -g fish_pager_color_description 665c54
set -g fish_pager_color_selected_background --background=d5c4a1
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS --border=rounded --info=inline-right \
--color=fg:#3c3836,bg:-1,hl:#b57614 \
--color=fg+:#3c3836,bg+:#d5c4a1,hl+:#b57614 \
--color=info:#665c54,prompt:#b57614,pointer:#427b58 \
--color=marker:#79740e,spinner:#b57614,header:#665c54 \
--color=border:#bdae93"
